[package]
name = "minitlsf"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]
edition = "2018"

[dependencies]
svgbobdoc = { version = "0.2.2" }

[dev-dependencies]
quickcheck_macros = "0.9.1"
quickcheck = "0.9.2"
env_logger = "0.7.1"
log = "0.4.8"
